# Generated by Django 5.0.6 on 2024-07-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogpost_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Опубликовать запись",
                verbose_name="Опубликовано",
            ),
        ),
    ]
