# Generated by Django 5.0.6 on 2024-07-15 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_blogpost_remove_product_views_counter"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogPost",
        ),
    ]
