# Generated by Django 4.2.2 on 2024-09-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Опубликовать запись",
                verbose_name="Опубликовано",
            ),
        ),
    ]
